version: '3.7'
services:
  mongodb:
    image: mongo:3.6
    container_name: mongodb
    hostname: mongodb
    tty: true
    environment:
      - 'MONGO_INITDB_ROOT_PASSWORD=ifextech@2023'
      - 'MONGO_INITDB_ROOT_USERNAME=dev'
      - 'MONGO_INITDB_ROOT_DATABASE=bancoteste1'
    ports:
      - 27017:27017
